class UserError(Exception):
    pass

class HabitError(Exception):
    pass